### ISSUE TITLE
Luma design

### ISSUE THREAD

**Issue by mageuser** [magekey/module-adc-popup#1]
How force to use Luma design?

**Comment by magekey** [comment]
@kauansoft not sure what the issue? magento 2 use the luma design by default.

**Comment by mageuser** [comment]
@magekey I am using another theme, the popup module is broken(style), I would like to use the luma css to display proper.

**Comment by magekey** [comment]
If your new theme is based on the default blank it should work. Anyway, I think the best way is to create new styles for your theme. You can find default luma styles here **view/frontend/web/css/source/_module.less**
