### ISSUE TITLE
False free shipping

### ISSUE THREAD

**Issue by yanncharlou** [magekey/module-adc-popup#2]
In some case, popup tell that shipping is free but in reality is not.
I've found this case using Owebia Shipping with rules that check country of shipping address. 
When running debugger, it appear that $totals['shipping'] can exists and $totals['shipping']->getValue() return NULL.

To prevent showing Free Shipping when there is simply no shipping rule matching yet. I suggest adding a simple test like below.

```php
/**
     * Get summary items
     *
     * @return array
     */
    public function getSummary()
    {
        $summaryItems = [];

        $qty = (int)$this->checkoutCart->getSummaryQty();
        $totals = $this->getQuote()->getTotals();

        if (isset($totals['subtotal'])) {
            $value = $totals['subtotal']->getValue();
            $summaryItems[] = [
                'label' => $qty . ' ' . __('product%1', $qty > 1 ? 's' : ''),
                'value' => $this->checkoutHelper->formatPrice($totals['subtotal']->getValue()),
            ];
        }

        if (isset($totals['shipping'])) {
            $value = $totals['shipping']->getValue();
            if($value){ //<-- ADD TEST HERE
                $summaryItems[] = [
                    'label' => $totals['shipping']->getTitle(),
                    'value' => __($value ? $this->checkoutHelper->formatPrice($value) : 'Free'),
                ];
            }
        }

        return $summaryItems;
    }
```

**Comment by magekey** [comment]
@yanncharlou the module doesn't use the shipping info anymore. The shipping method and price depend on shipping address you should add in the cart or checkout pages. Please check the latest release 2.0.5.

**Comment by magekey** [comment]
![alt text](https://raw.githubusercontent.com/magekey/module-adc-popup/master/docs/images/popup.png)

**Comment by yanncharlou** [comment]
@magekey Ok great.
It seems module is not updated on Magento Marketplace so it won't update with regular composer update.
Using composer require magekey/module-adc-popup still get 2.0.3.
I had to use  composer require magekey/module-adc-popup 2.0.5 to get the latest version.
