### ISSUE TITLE
Cart missing price when only one product

### ISSUE THREAD

**Issue by ricatt** [magekey/module-adc-popup#3]
When adding a product to the cart and it is the first product,then subtotalAmount comes back at zero and items comes with product_price of zero as well. After adding the second product, then we get the prices for both products with no further issues. It is just when adding the first product. Any idea for how to circumvent this issue or even solve it?

**Comment by magekey** [comment]
@ricatt which Magento version are you using?

**Comment by ricatt** [comment]
@magekey it's 2.2.6.

**Comment by magekey** [comment]
@ricatt The module uses the same cart data as a minicart sidebar in the header. Please check your code and make sure it works correctly without errors.
