### ISSUE TITLE
Product images are not proportional

### ISSUE THREAD

**Issue by crdt** [magekey/module-adc-popup#5]
Product images in popup are not proportionally resized in Magento 2.3.1 with module-adc-popup
release 2.0.6

**Comment by magekey** [comment]
@crdt Please provide more details about your issue. The module has been tested on Magento 2.3.1 with Samples Data successfully.

**Comment by magekey** [comment]
@crdt Please check the view.xml inside the module. There are 2 paths you can update based on your requirements: **mgk_adcpopup_cart_single** and **mgk_adcpopup_cart_multi**.
Apply changes to your custom theme.
